apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: nuvem
spec:
  selector:
    matchLabels:
      app: nuvem
      tier: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nuvem
        tier: mongodb
    spec:
      containers:
      - image: mongo:latest
        name: mongodb
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: password
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-pv-claim
