apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: default
  labels:
    app: nuvem
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    app: nuvem
    tier: mongodb
  type: ClusterIP
