apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: default
  labels:
    app: nuvem
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: nuvem
    tier: api
  type: LoadBalancer